apiVersion: v1
kind: Pod
metadata:
  name: http-client-pod
  namespace: devops-test-master
spec:
  containers:
  - image: rltp/http-client
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo Done Deploying http-client; sleep 3600;done"]
    imagePullPolicy: Never
    name: http-client
  restartPolicy: Always