apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: devops-test-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Never
        name: mongo
        args: ["--dbpath","/data/db"]

        livenessProbe:
          exec:
            command:
              - mongosh
              - --quiet
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6

        readinessProbe:
          exec:
            command:
              - mongosh
              - --quiet
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6

        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
          
        volumeMounts:
        - name: "mongo-data"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data"
        persistentVolumeClaim:
          claimName: "mongodb-pvc"