apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: devops-test-master
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  hostPath:
    path: /data/mongo