apiVersion: v1
kind: Service
metadata:
  name: api-service-node
  namespace: devops-test-master 
spec:
  type: NodePort 
  ports:
    - name: api-service-80
      protocol: TCP
      port: 80
      targetPort: sample-api-svc
  selector:
    app: api

---

apiVersion: v1
kind: Service
metadata:
  name: api-service-cluster
  namespace: devops-test-master 
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: api